INSERT INTO USERS (USER_ID, FULL_NAME, PASSWORD, PROFILE, AUTHORITIES, PRIVATE_SECRET, PUBLIC_SECRET) VALUES ('asterieks@gmail.com', 'Name Surname', '1', 'REPORTER', 'ROLE_REPORTER','','');
INSERT INTO USERS (USER_ID, FULL_NAME, PASSWORD, PROFILE, AUTHORITIES, PRIVATE_SECRET, PUBLIC_SECRET) VALUES ('lead@gmail.com', 'Name1 Surname1', '2','LEAD', 'ROLE_MANAGER','','');
INSERT INTO USERS (USER_ID, FULL_NAME, PASSWORD, PROFILE, AUTHORITIES, PRIVATE_SECRET, PUBLIC_SECRET) VALUES ('test@gmail.com', 'Name2 Surname2', '3','REPORTER', 'ROLE_REPORTER','','');
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER,STATE,STATE_DATE) VALUES ('1', 'XXX', 'lead@gmail.com', null, 'asterieks@gmail.com','Reported','2017-10-10 00:00:00');
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER,STATE,STATE_DATE) VALUES ('2', 'YYY', 'lead@gmail.com', null, 'asterieks@gmail.com','Reported','2017-10-10 00:00:00');
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER,STATE,STATE_DATE) VALUES ('3', 'ZZZ', 'lead@gmail.com', null, 'test@gmail.com','Reported','2017-10-10 00:00:00');
INSERT INTO REPORTS (REPORT_ID, PROJECT_ID, REVIEW_PART,ISSUE_PART,PLAN_PART,CREATION_DATE,REPORTED_BY) VALUES ('1', '1',  'prevreviewX', 'previssueX', 'prevplanX','2017-10-10 00:00:00','asterieks@gmail.com');
INSERT INTO REPORTS (REPORT_ID, PROJECT_ID, REVIEW_PART,ISSUE_PART,PLAN_PART,CREATION_DATE,REPORTED_BY) VALUES ('2', '1',  'review', 'issue', 'plan','2017-10-16 00:00:00','asterieks@gmail.com');
