--clear tables
DROP TABLE REPORTS;
DROP TABLE PROJECTS;
DROP TABLE USERS;
--clear sequence
DROP SEQUENCE user_report_id_seq;
DROP SEQUENCE user_report_record_id_seq;

--tables
CREATE TABLE USERS
("USER_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"FULL_NAME" VARCHAR2(150 BYTE) NOT NULL ENABLE,
"ROLE" VARCHAR2(150 BYTE),
PRIMARY KEY ("USER_ID"));

CREATE TABLE PROJECTS
("PROJECT_ID" NUMBER NOT NULL ENABLE,
"PROJECT_NAME" VARCHAR2(255 BYTE),
"RESPONSIBLE_TEAM_LEADER" VARCHAR2(255 BYTE),
"MANAGER" VARCHAR2(255 BYTE),
"REPORTER" VARCHAR2(255 BYTE),
PRIMARY KEY ("PROJECT_ID"));

CREATE TABLE REPORTS
("REPORT_ID" NUMBER NOT NULL ENABLE,
"PROJECT_ID" NUMBER NOT NULL ENABLE,
"REVIEW_PART" VARCHAR2(4000 BYTE),
"ISSUE_PART" VARCHAR2(4000 BYTE),
"PLAN_PART" VARCHAR2(4000 BYTE),
"CREATION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
PRIMARY KEY ("REPORT_ID"));

commit;

--sequences
CREATE SEQUENCE user_report_id_seq
  MINVALUE 1 MAXVALUE 999999999999999
  START WITH 1
  INCREMENT BY 1
  NOORDER NOCYCLE;

commit;

--test instances
INSERT INTO USERS (USER_ID, FULL_NAME, ROLE) VALUES ('asterieks@gmail.com', 'Maksym Sokil', '');
INSERT INTO USERS (USER_ID, FULL_NAME, ROLE) VALUES ('lead@gmail.com', 'Yevhenii Reva', '');
INSERT INTO USERS (USER_ID, FULL_NAME, ROLE) VALUES ('tester@gmail.com', 'A Person', '');

INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER) VALUES ('1', 'Reportum Test',  'lead@gmail.com', '', 'asterieks@gmail.com');
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER) VALUES ('2', 'Test Project',   'lead@gmail.com', '', 'tester@gmail.com');
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER) VALUES ('3', 'Second Project', 'lead@gmail.com', '', 'asterieks@gmail.com');

commit;