--tables
DROP TABLE USERS;
CREATE TABLE USERS
("USER_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"FULL_NAME" VARCHAR2(150 BYTE) NOT NULL ENABLE,
"ROLE" VARCHAR2(150 BYTE),
PRIMARY KEY ("USER_ID"));

DROP TABLE PROJECTS;
CREATE TABLE PROJECTS
("PROJECT_ID" NUMBER NOT NULL ENABLE,
"PROJECT_NAME" VARCHAR2(255 BYTE),
"RESPONSIBLE_TEAM_LEADER" VARCHAR2(255 BYTE),
"MANAGER" VARCHAR2(255 BYTE),
"REPORTER" VARCHAR2(255 BYTE),
"STATE" VARCHAR2(255 BYTE),
"STATE_DATE" TIMESTAMP (6),
PRIMARY KEY ("PROJECT_ID"));

--clear tables
DROP TABLE REPORTS;
CREATE TABLE REPORTS
("REPORT_ID" NUMBER NOT NULL ENABLE,
"PROJECT_ID" NUMBER NOT NULL ENABLE,
"REVIEW_PART" VARCHAR2(4000 BYTE),
"ISSUE_PART" VARCHAR2(4000 BYTE),
"PLAN_PART" VARCHAR2(4000 BYTE),
"CREATION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
"REPORTED_BY" VARCHAR2(255 BYTE),
PRIMARY KEY ("REPORT_ID"));

commit;

--sequences
DROP SEQUENCE user_report_id_seq;
CREATE SEQUENCE user_report_id_seq
  MINVALUE 1 MAXVALUE 999999999999999
  START WITH 1
  INCREMENT BY 1
  NOORDER NOCYCLE;

commit;

--test instances
INSERT INTO USERS (USER_ID, FULL_NAME, ROLE) VALUES ('asterieks@gmail.com', 'Maksym Sokil', 'REPORTER');
INSERT INTO USERS (USER_ID, FULL_NAME, ROLE) VALUES ('lead@gmail.com', 'Yevhenii Reva', 'LEAD');
INSERT INTO USERS (USER_ID, FULL_NAME, ROLE) VALUES ('tester@gmail.com', 'A Person', '');

INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER,STATE,STATE_DATE) VALUES ('1', 'BAT',  'lead@gmail.com', '', 'asterieks@gmail.com','Delayed','');
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER,STATE,STATE_DATE) VALUES ('2', 'EFP',   'lead@gmail.com', '', 'tester@gmail.com','Delayed','');
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, RESPONSIBLE_TEAM_LEADER,MANAGER,REPORTER,STATE,STATE_DATE) VALUES ('3', 'ULAS', 'lead@gmail.com', '', 'asterieks@gmail.com','Delayed','');

commit;