CREATE USER REPORT1 IDENTIFIED BY REPORTUM;
/
GRANT UNLIMITED TABLESPACE TO REPORT1;
/
GRANT CONNECT TO REPORT1;
/
GRANT CREATE SESSION TO REPORT1;
/
GRANT CREATE TABLE TO REPORT1
/
GRANT CREATE PROCEDURE TO REPORT1
/
GRANT CREATE TRIGGER TO REPORT1
/
GRANT CREATE VIEW TO REPORT1
/
GRANT CREATE SEQUENCE TO REPORT1
/
GRANT CREATE VIEW TO REPORT1
/
GRANT DELETE ANY TABLE TO REPORT1
/
GRANT DROP ANY TABLE TO REPORT1
/
GRANT DROP ANY PROCEDURE TO REPORT1
/
GRANT DROP ANY TRIGGER TO REPORT1
/
GRANT DROP ANY VIEW TO REPORT1
/
GRANT ALTER ANY TABLE TO REPORT1
/
GRANT ALTER ANY TABLE TO REPORT1
/
GRANT ALTER ANY PROCEDURE TO REPORT1
/
GRANT ALTER ANY TRIGGER TO REPORT1
/
COMMIT;