CREATE USER REPORTUM_REPOS IDENTIFIED BY Password1;
/
GRANT UNLIMITED TABLESPACE TO REPORTUM_REPOS;
/
GRANT CONNECT TO REPORTUM_REPOS;
/
GRANT CREATE SESSION TO REPORTUM_REPOS;
/
GRANT CREATE TABLE TO REPORTUM_REPOS
/
GRANT CREATE PROCEDURE TO REPORTUM_REPOS
/
GRANT CREATE TRIGGER TO REPORTUM_REPOS
/
GRANT CREATE VIEW TO REPORTUM_REPOS
/
GRANT CREATE SEQUENCE TO REPORTUM_REPOS
/
GRANT CREATE VIEW TO REPORTUM_REPOS
/
GRANT DELETE ANY TABLE TO REPORTUM_REPOS
/
GRANT DROP ANY TABLE TO REPORTUM_REPOS
/
GRANT DROP ANY PROCEDURE TO REPORTUM_REPOS
/
GRANT DROP ANY TRIGGER TO REPORTUM_REPOS
/
GRANT DROP ANY VIEW TO REPORTUM_REPOS
/
GRANT ALTER ANY TABLE TO REPORTUM_REPOS
/
GRANT ALTER ANY TABLE TO REPORTUM_REPOS
/
GRANT ALTER ANY PROCEDURE TO REPORTUM_REPOS
/
GRANT ALTER ANY TRIGGER TO REPORTUM_REPOS
/
COMMIT;