CREATE USER REPORT IDENTIFIED BY REPORTUM;
/
GRANT UNLIMITED TABLESPACE TO REPORT;
/
GRANT CONNECT TO report;
/
GRANT CREATE SESSION TO REPORT;
/
GRANT CREATE TABLE TO REPORT
/
GRANT CREATE PROCEDURE TO REPORT
/
GRANT CREATE TRIGGER TO REPORT
/
GRANT CREATE VIEW TO REPORT
/
GRANT CREATE SEQUENCE TO REPORT
/
GRANT CREATE VIEW TO REPORT
/
GRANT DELETE ANY TABLE TO REPORT
/
GRANT DROP ANY TABLE TO REPORT
/
GRANT DROP ANY PROCEDURE TO REPORT
/
GRANT DROP ANY TRIGGER TO REPORT
/
GRANT DROP ANY VIEW TO REPORT
/
GRANT ALTER ANY TABLE TO REPORT
/
GRANT ALTER ANY TABLE TO REPORT
/
GRANT ALTER ANY PROCEDURE TO REPORT
/
GRANT ALTER ANY TRIGGER TO REPORT
/
COMMIT;